[package]
name = "skym"
version = "0.1.0"
edition = "2021"

[lib]
name = "skym"
crate-type = ["cdylib"]

[dependencies]
skim = "0.16.1"

[dependencies.pyo3]
version = "0.20.0"
features = ["abi3-py38"]
